
//Window
#define FRAMES_PER_SECOND 30
const int FRAME_TIME = 1000 / FRAMES_PER_SECOND;


//grille
#define TAILLE_GRILLE_LIGNE 16
#define TAILLE_GRILLE_COLONNE 25
const int NOMBRE_BOMBES_GRILLE = (TAILLE_GRILLE_LIGNE*TAILLE_GRILLE_COLONNE)*0.25;
#define TAILLE_CASE 50
enum{MASQUE,MASQUE_AVEC_BOMBES,BOMBE,LIBRE,DANGER_AVEC_LIBRE_AUTOUR,DANGER_SANS_LIBRE_AUTOUR, DRAPEAU_AVEC_BOMBES, DRAPEAU_SANS_BOMBES};
