
//Window
#define FRAMES_PER_SECOND 30
const int FRAME_TIME = 1000 / FRAMES_PER_SECOND;


//grille
#define TAILLE_GRILLE_LIGNE 16
#define TAILLE_GRILLE_COLONNE 25
const int NB_BOMBES = (TAILLE_GRILLE_LIGNE*TAILLE_GRILLE_COLONNE)*0.15;
#define TAILLE_CASE 50
enum{MASQUE,BOMBE,VIDE,};
