#define VITESSE_DEPLACEMENT 0.18F
#define SENSIBILITE_CAMERA 0.08F
#define HAUTEUR_CAMERA_DEBOUT 3.5F
#define MAX_Y_AXE_CIBLE 2.8F

#define START_PX 0.0F //AXE X
#define START_PY 3.5F // hauteur CAMERA
#define START_PZ 19.0F // AXE Y
#define START_CIBLE_Y 0.0F // REGARDE SUR AXE HAUTEUR
#define START_CIBLE_X M_PI// REGARDE SUR AXE X
#define START_OUVERTURE 70.0F //OUVERTURE CAMERA
