all: main.c
	gcc main.c ../../include/libWeb.c import.c ../../games/3_flappy_bird/flappy_bird.c -o main -std=c99 -framework OpenGL -framework GLUT -lm -lSDL2 -lassimp -lSDL2_image -lSDL2_mixer -lSDL2_ttf -L/usr/local/opt/openssl/lib -lcrypto -lcurl
